version: '2'

volumes:
  esdata1:
    driver: local
  psql-bmo_poc-data:
    driver: local

services:
  database:
    image: postgres:9.5.2
    ports:
      - 5432:5432
    volumes:
      - psql-bmo_poc-data:/var/lib/postgresql/data
      - .:/shared
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
